#!/usr/bin/env python3

import random
import string

N=1_000_000
K = 16

STRINGS = set()

f = open("../bench/rand_keys.c", "w")

def rand_string(length):
    res = "".join(random.choices(string.ascii_letters + string.digits, k=length))
    return res

for i in range (0, N):
    s = rand_string(K)
    STRINGS.add(s)

s = "const char* keys[] = {\n"

f.write(s)

for val in STRINGS:
    f.write("\"" + val + "\",\n")

f.write("};")

f.close()
